version: '3'
services:
    tex:
        build: ./tex
        hostname: texuser
        container_name: tex
        volumes:
            -  ../graduation-thesis:/mnt/graduation-thesis
        command: bash -c "cd /mnt/graduation-thesis/src && platex main.tex && dvipdfmx main.dvi"

